require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - bin/**/*
    - db/schema.rb
  NewCops: enable

Layout/LineLength:
  Max: 240

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false
